import type { Metadata } from "next";
import "@/styles/global.sass";
import SWRProvider from "@/providers/swr";
import ThemeProvider from "@/dataslot-ui/provider";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next appa",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <ClerkProvider>
      <html lang="th">
        <head>
          <link rel="stylesheet" href="https://kit.fontawesome.com/190a9bf6af.css" crossOrigin="anonymous"></link>
        </head>
        <body>
          <SWRProvider>
            <ThemeProvider>
              <Navbar />
              {children}
            </ThemeProvider>
          </SWRProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
